/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ScoreEntry = IDL.Record({
  'difficulty' : IDL.Text,
  'score' : IDL.Nat,
  'timestamp' : Time,
  'playerName' : IDL.Text,
  'ageGroup' : IDL.Text,
});
export const ScoreEntryInput = IDL.Record({
  'difficulty' : IDL.Text,
  'score' : IDL.Nat,
  'playerName' : IDL.Text,
  'ageGroup' : IDL.Text,
});

export const idlService = IDL.Service({
  'getGlobalTop10' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
  'getTop10ByAgeGroup' : IDL.Func([IDL.Text], [IDL.Vec(ScoreEntry)], ['query']),
  'submitScore' : IDL.Func([ScoreEntryInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ScoreEntry = IDL.Record({
    'difficulty' : IDL.Text,
    'score' : IDL.Nat,
    'timestamp' : Time,
    'playerName' : IDL.Text,
    'ageGroup' : IDL.Text,
  });
  const ScoreEntryInput = IDL.Record({
    'difficulty' : IDL.Text,
    'score' : IDL.Nat,
    'playerName' : IDL.Text,
    'ageGroup' : IDL.Text,
  });
  
  return IDL.Service({
    'getGlobalTop10' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
    'getTop10ByAgeGroup' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ScoreEntry)],
        ['query'],
      ),
    'submitScore' : IDL.Func([ScoreEntryInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };